<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZrz1skw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZrz1skw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZrz1skw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZrz1skw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZrz1skw\appProdProjectContainer(array(
    'container.build_hash' => 'Zrz1skw',
    'container.build_id' => '3f7486f0',
    'container.build_time' => 1533709725,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZrz1skw');
