<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS8dix9u\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS8dix9u/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerS8dix9u.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerS8dix9u\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerS8dix9u\appDevDebugProjectContainer(array(
    'container.build_hash' => 'S8dix9u',
    'container.build_id' => 'cc211681',
    'container.build_time' => 1534367321,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerS8dix9u');
